---
title: Exploration of the Common Factors Among the Highest Paying Information Technology
  and STEM Jobs
author: "Crispin Corpuz, Ken Drucker, Connor Moorhous, Josh Reynoso, Alexis Walther"
date: "February 27, 2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
  As technology continues to spread into countless parts of everyday life, it is easy to marvel at the fact that there are numerous people, teams, and organizations behind its development. While it is true that the jobs and organizations in the tech industry have become lucrative, it is also true that not all jobs are created equal in terms of salary. This raises the question about what factors contribute to the higher salaries in tech and STEM, in addition to what factors contribute to wage discrimination and quality of life for professionals. For context, some jobs in these fields could possibly pay higher salaries than others according to a multitude of factors that could include education level, years of experience, supply and demand for individuals qualified for these jobs, and many more. 
    
  The research in this project seeks to answer three questions. First, are there common factors between tech jobs that significantly raise their salary, and what are they? Finding categorical trends among the salaries of IT professionals that can provide deeper insight than the surface level stereotypes of moving upward through the corporate chain or small, startup company successes would be particularly valuable. Second—which is almost a subcategory of first question because of its likely proximity to the same data—is wage discrimination present in STEM and the tech industry? While there are social aspects that confound the information needed to draw a conclusion to answer this question and that are difficult to quantify in data sets, there is value for emerging professionals in being able to provide insight into this topic from an objective data analysis perspective. Third, what are the best cities for STEM jobs in terms of salary, cost of living, and other quality of life factors? This question is in the same spirit as the first question in that building trends and profiles is valuable for quick information digestion. However, it differs in the sense that answering this question identifies specific tech industry hotspots that can help young professionals discover feasible paths on which to start and build their career.
    
  The answers and conclusions generated from this research and data analysis, as mentioned, will be a useful tool for a wide range of young individuals from high school students to college students and graduates to individuals looking to change careers into the tech industry. Interaction with this information can range from a detailed report to a simple web application in order to educate this demographic on the nuances behind jobs in the tech industry and STEM.


# About the Data
  The first data source for this report, titled “Data Science and STEM Salaries,”\footnote{https://www.kaggle.com/datasets/jackogozaly/data-science-and-stem-salaries} is a compilation of data from levels.fyi, a website used for reporting and researching salaries, that is located on kaggle.com. The data set, with 29 columns and over 62,000 entries, contains salary data – including experience, company, location, and demographic information including gender, race, and education – for 15 STEM roles between 2017 and 2021. This large and diverse data set aids the discovery of any common factors of the highest paid positions in STEM careers. Additionally, the demographic information in this set helps find the presence of any wage discrimination based on gender or race, and the location information helps determine the best cities for STEM jobs.
  
  The second source, titled "Data Science Jobs Salaries Dataset,"\footnote{https://www.kaggle.com/datasets/saurabhshahane/data-science-jobs-salaries} is another data set found on kaggle.com. This data source contains salary information from ai-jobs.net, another salary reporting site similar to levels.fyi. While this data set lacks city location and demographic information, it still contains experience, country location, and company size for 43 data science related positions. Used in conjunction with the first source, this second source introduces data surrounding more niche positions that can be used to find common factors of the highest paid STEM jobs.
  
  The final source is teleport.org\footnote{https://teleport.org/cities/}, a site that calculates and reports quality of life metrics for cities across the globe. The site ranks cities in 17 categories including cost of living, commute, safety, and more. The data found on this site, which can be accessed using a public API, provides another perspective that benefits the evaluation of the best cities for STEM careers.


# Biweekly Timeline
| Date    | Person           | Task                                                                                   |
| ------- | ----------------| --------------------------------------------------------------------------------------|
| 2/27    | Entire Group    | Complete Project Proposal                                                              |
| 2/27    | Crispin Corpuz  | Submit proposal                                                                        |
| 3/13    | Crispin Corpuz  | Clean and summarize “Data Science and STEM Salaries” dataset                            |
| 3/13    | Ken Drucker     | Clean and summarize “Data Science Jobs” dataset                                        |
| 3/13    | Connor Moorhous | Scrape, clean and summarize “Teleport.org” data                                        |
| 3/27    | Entire Group    | - Finalize midterm report                                                              |
|         |                 | - Explain how data was cleaned and reshaped                                            |
|         |                 | - Explain basic data analysis and visualizations done                                 |
|         |                 | - Describe obstacles met and how they were handled                                     |
| 4/10    | Entire Group    | Determine the project’s data product scope                                             |
| 4/10    |                 |                                                                                        |
| 4/10    | Crispin Corpuz  | Create data visualizations for final report                                            |
| 4/24    | Entire Group    | Update work based on any critique received from midterm report                         |
|         |                 | Bring findings together into a rough draft of the final report, including any conclusions |
|         |                 | Begin to split topics up by group member and begin organizing for the final presentation |
| 5/8     | Entire Group    | Complete final draft of report; Record and combine individual presentations into one 10-minute long presentation |
